name: 'coverage'
on:
  push:
    branches:
      - main

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.6
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install numpy
        - name: Run tests with pytest
        run: python unittest/test_lib.py
